### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by PuercoPop** [LispLima/linedit#1]
Tracking Issues:
- [x] Remove terminfo from the repository (#6)
- [x] Remove trailing lines and tabs (#4) (#5)
- [ ] Reader hook patch
- [ ] Migrate to CFFI
- [x] Remove Madeira port in favor of ASDF feature expressions (#7)
- [ ] Remove terminal glue
- [ ] Remove anaphoric variants in favor of alexandrias when-let if-let
- [ ] Scour through tokenrove's PR for unmerged changes from CVS

It may be a good idea to reorganize the code into directories for related functionality and split stuff like completion and paren navigation into its own system
